name: "Style repository using Black"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Lint Python Code"
        uses: psf/black@stable
        with:
            options: "--verbose"
            src: "./"

      - name: "Push Restyled Changes"
        uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
        with:
          message: 'Restyled code'
          push: true
