name: "Style repository using Black"

on:
  push:
    branches:
      - main
      - feature/update-workflows
  pull_request:
    branches:
      - main
      - feature/update-workflows
  pull_request_target:
    branches:
      - main
      - feature/update-workflows

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Python Code
        uses: psf/black@stable
        with:
            options: "--verbose"
            src: "./"

      - name: Push Restyled Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
