name: "Sort Imports"

on:
  push:
    branches:
      - main
      - feature/update-workflows
  pull_request:
    branches:
      - main
      - feature/update-workflows
  pull_request_target:
    branches:
      - main
      - feature/update-workflows

jobs:
  sort-imports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Sort Imports
        uses: isort/isort-action@master
        with:
          isortVersion: 5.10.1
          requirementsFiles: "requirements.txt"
          configuration: ""

      - name: Push Restyled Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sorted Imports
